import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script"; // AJOUT

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* --- OneSignal SDK et init (version OneSignal v16) --- */}
        <Script
          src="https://cdn.onesignal.com/sdks/web/v16/OneSignalSDK.page.js"
          strategy="afterInteractive"
        />
        <Script id="onesignal-init" strategy="afterInteractive">
          {`
            window.OneSignalDeferred = window.OneSignalDeferred || [];
            OneSignalDeferred.push(async function(OneSignal) {
              await OneSignal.init({
                appId: "2a6dc7fc-1f0e-4f6c-9218-8b7addca1b83",
              });
            });
          `}
        </Script>
        {/* --- FIN OneSignal --- */}
        {children}
      </body>
    </html>
  );
}
